### ISSUE TITLE
Missing diff faces

### ISSUE THREAD

**Issue by FelipeLema** [jbharat/zeno-theme#1]
`diff-refine-added`, `diff-refine-changed` and `diff-refine-removed`.

To test them, open a diff file and navigate through it.

**Comment by rokrdev** [comment]
Thanks for reporting. I will add them.

**Comment by jbharat** [comment]
@FelipeLema can you attach a screenshot. I have never used them so I am not sure how they will look. If you provide a screenshot I can think of the colour to use.

**Comment by rokrdev** [comment]
@FelipeLema There was a release yesterday. Can you have a look and see if these faces are proper

**Comment by FelipeLema** [comment]
Here's a diff with refinement using default colors on 24bit-color terminal
![image](https://user-images.githubusercontent.com/1232306/47668284-ca3e9600-db86-11e8-82b0-09804dc14e2d.png)

And here's the same diff with zeno-theme @ 0914c4a5b1b
![image](https://user-images.githubusercontent.com/1232306/47668383-0a9e1400-db87-11e8-8b6a-dde3f28c71b9.png)

I can tell that it's making the refinement on both because when I run `customize-face` it offers `diff-refine-added` on the `zeno` word, although because the second one has the same face as `diff-added` it doesn't show.

You can try yourself with a diff file and doing `M-x diff-refine-hunk` with the cursor on either changed word.

**Comment by Etenil** [comment]
@FelipeLema I believed I fixed this one. Opened a PR.
